# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-27 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='default_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Address', verbose_name='默认地址'),
        ),
    ]
